version: '3'

services:
  node1:
    command: node index.js
    build: .
    ports:
      - 1234:1234/udp
      - 3000:3000/tcp
    environment:
      IP_ADDRESS: 172.20.0.3
      ACTIVE_NODE_ADDRESS: 172.20.0.2
      ACTIVE_NODE_PORT: 1234
    volumes:
      - ./:/usr/src/app

  node2:
    command: node index.js
    build: .
    ports:
      - 1235:1234/udp
      - 3001:3000/tcp
    environment: 
      IP_ADDRESS: 172.20.0.2
      ACTIVE_NODE_ADDRESS: 172.20.0.3
      ACTIVE_NODE_PORT: 1234
    volumes:
      - ./:/usr/src/app
